project:
  type: website

website:
  title: "Reproducibility Check"
  repo-url: https://github.com/lmu-osc/ReproducibilityCheck
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: literature.bib

